# Generated by Django 2.2.10 on 2020-12-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('company_name', models.CharField(max_length=250, verbose_name='Company')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('cv', models.FileField(upload_to='pdf/%y/%m/%d')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
